Makefile: Stop passing *.pm directories to `bin/checkstyle.sh`
The situation after a test run is this in the file system:
> # find . -name \*.pm -type d
> ./tests/genhtml/simple/criteria.pm
> ./tests/genhtml/simple/criteria_signoff.pm

The result is `make checkstyle` failing like this:
> # make checkstyle
> [..]
> fatal: path 'tests/genhtml/simple/criteria.pm' exists on disk, but not in 'HEAD'
> Error: No version of tests/genhtml/simple/criteria.pm found in git ref HEAD
> saw mismatch for tests/genhtml/simple/criteria.pm
> [..]
> fatal: path 'tests/genhtml/simple/criteria_signoff.pm' exists on disk, but not in 'HEAD'
> Error: No version of tests/genhtml/simple/criteria_signoff.pm found in git ref HEAD
> saw mismatch for tests/genhtml/simple/criteria_signoff.pm
> [..]
> make: *** [Makefile:332: checkstyle] Error 1

Now these directories are no longer passed by mistake.